services:

  bchn:
    image: theretromike/nodes:bitcoincash
    container_name: bchn
    restart: unless-stopped
    network_mode: host
    volumes:
      - bch-solo-pool_bchn-data:/root/.bitcoin

  postgres:
    image: postgres:16
    container_name: mc-postgres
    restart: unless-stopped
    network_mode: host
    environment:
      POSTGRES_USER: miningcore
      POSTGRES_PASSWORD: ${APP_SEED}
      POSTGRES_DB: miningcore
    volumes:
      - mc-postgres-data:/var/lib/postgresql/data

  miningcore:
    image: theretromike/miningcore
    container_name: miningcore
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/config.json:/app/config.json
      - ${APP_DATA_DIR}/coins.json:/app/build/coins.json

  web:
    image: nginx:alpine
    container_name: pool-web
    restart: unless-stopped
    ports:
      - "3080:80"
    volumes:
      - ${APP_DATA_DIR}/web:/usr/share/nginx/html:ro
      - ${APP_DATA_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  dozzle:
    image: amir20/dozzle:latest
    container_name: pool-dozzle
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  bch-solo-pool_bchn-data:
    external: true
  mc-postgres-data:
