version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: apathecmines-bch-node_web_1
      APP_PORT: 8080
  web:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - node
  node:
    image: theretromike/nodes:bitcoincash
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/.bitcoincash:/root/.bitcoin
    ports:
      - 8334:8334
      - 9002:9002
      - 7002:7002
    entrypoint: "bitcoind -printtoconsole -server -txindex=1 -zmqpubhashblock=tcp://127.0.0.1:7002 -rpcbind=0.0.0.0 -rpcport=9002 -rpcallowip=0.0.0.0/0 -port=8334 -rpcuser=apathecpool -rpcpassword=Xk9mT4vQp2wL7nRz8Hc3jYf6sDb1u"
