server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /rest/ {
        proxy_pass http://127.0.0.1:8332/rest/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
